"""Ajuste tamanho campos

Revision ID: 5f2264eb9c34
Revises: 
Create Date: 2025-03-15 17:11:31.920388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2264eb9c34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_restaurante', sa.String(length=120), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('mensagem_rodape', sa.String(length=255), nullable=True),
    sa.Column('impressora_cozinha', sa.String(length=120), nullable=True),
    sa.Column('impressora_bar', sa.String(length=120), nullable=True),
    sa.Column('imprimir_pedidos_cozinha', sa.Boolean(), nullable=True),
    sa.Column('imprimir_pedidos_bar', sa.Boolean(), nullable=True),
    sa.Column('categorias_cozinha', sa.String(length=500), nullable=True),
    sa.Column('categorias_bar', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('senha_hash', sa.String(length=512), nullable=False),
    sa.Column('cargo', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixa_diario.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempo_preparo_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tempo_padrao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_comanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comanda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_comanda_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tempo_estimado', sa.Integer(), nullable=True),
    sa.Column('inicio_preparo', sa.DateTime(), nullable=True),
    sa.Column('fim_preparo', sa.DateTime(), nullable=True),
    sa.Column('observacoes_cozinha', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['item_comanda_id'], ['item_comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_pedido')
    op.drop_table('item_comanda')
    op.drop_table('tempo_preparo_padrao')
    op.drop_table('comanda')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('mesa')
    op.drop_table('configuracao_sistema')
    op.drop_table('caixa_diario')
    # ### end Alembic commands ###
